config/routes.rb
Rails.application.routes.draw do
  
  
  root "tasks#index"
  devise_for :users
  post '/tasks/guest_sign_in', to: 'homes#new_guest'

  

  resources :users, only: [:edit, :update, :destroy]
  resources :tasks, only: [:index,:new,:create,:show,:destroy] do
    collection do
      get 'search'
    end
    resources :todos,only: [:index,:new,:create,:destroy] 
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :todos, dependent: :delete_all
  validates :content, presence: true

  # 検索機能
  def self.search(search)
    return Task.all unless search
    Task.where('content LIKE(?)',"%#{search}%")
  end

end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :task
  belongs_to :user
  validates :todo, presence: true
  validates :enddate, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :tasks ,foreign_key:true
  has_many :todos
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_filter :set_request_from

  def set_request_from
    if session[:request_from]
      @request_from = session[:request_from]
    end
    # 現在のURLを保存しておく
    session[:request_from] = request.original_url
  end

  def return_back
    if request.referer
      redirect_to :back and return true
    elsif @request_from
      redirect_to @request_from and return true
    end
  end

  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController 

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = "ゲストユーザー"
      user.password = SecureRandom.urlsafe_base64
      
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :move_to_index, except: [:index, :show, :search]

  def index
    @tasks =Task.all
    @task =Task.new
  end

  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to root_path(@task), notice: 'ToDoが作成されました'
    else
      redirect_to root_path(@task), alert: 'ToDoを入力してください。'
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to root_path(@task), alert: 'ToDoが削除されました'
  end

  def show
    @task = Task.find(params[:id])
    @today = Date.today
  end

  def search
    @tasks = Task.search(search_params)
  end

  private

  def task_params
    params.require(:task).permit(:content).merge(user_id: current_user.id)
  end

  def search_params
    params.permit(:search)
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos =Todo.all
    @todo =Todo.new
  end

  def create
    @todo = Todo.create(todo_params)
    if @todo.save
      flash[:notice]='ToDoが作成されました'
      return_back and return
      
    else
      flash[:alert]='ToDoを入力してください'
      return_back and return
    end
  end

  def destroy
    todo = Todo.find(params[:id])
    flash[:alert]='ToDoを削除しました'
    todo.destroy
    return_back and return 
  end

  private
  def todo_params
    params.require(:todo).permit(:todo,:enddate).merge(user_id: current_user.id, task_id: params[:task_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mytask
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/tasks/index.html.haml
.task
  .task__header
    .task__header__box1
      TODOリスト
    = form_tag search_tasks_path,method: 'get',class:"task__header__box2__search" do
      = "ToDo検索" 
      = text_field_tag :search,'',class:'task__header__box2__search__text',placeholder: "検索ワード入力"
      = submit_tag '検索',content: :nil,class:"task__header__box2__search__text"
    .task__header__box2__name
      = link_to edit_user_path(current_user) do
        = current_user.name
   
  .task__main
    .task__main__new
      = form_for [@task] do |f|
        = f.text_field :content, class: 'task__main__new__form', placeholder: '新しいToDoを入力してください'
        = f.submit '作成', class: 'task__main__new__btn'
    .task__main__list
      - @tasks.each do |task|
        .todo__main__list__to-do
          = link_to "#{task.content}", "/tasks/#{task.id}", method: :get
          = link_to "/tasks/#{task.id}", method: :delete do
            = icon('fas', 'trash-alt', class: 'todo__main__list__to-do__delete')
          

    

app/views/tasks/search.html.haml
.search
  .search__header
    .search__header__box1
      TODOリスト
    = form_tag search_tasks_path,method: 'get',class:"search__header__box2__search" do
      = "ToDo検索" 
      = text_field_tag :search,'',class:'task__header__box2__search__text',placeholder: "検索ワード入力"
      = submit_tag '検索',content: :nil,class:"search__header__box2__search__text"
    .search__header__box2
      .search__header__box2__name
        = link_to edit_user_path(current_user) do
          = current_user.name
      = link_to "/", method: :get do
        = icon('fas', 'undo-alt', class: 'search__header__box2__return')


  .search__main
  .search__main__list
    - @tasks.each do |task|
      .search__main__list__to-do
        = link_to "#{task.content}", "/tasks/#{task.id}", method: :get
        = link_to '削除', "/tasks/#{task.id}", method: :delete

app/views/tasks/show.html.haml
.todo
  .todo__header
    .todo__header__box1
      =@task.content
    .todo__header__box2
      .todo__header__box2__name
        = current_user.name
      = link_to "/", method: :get do
        = icon('fas', 'undo-alt', class: 'todo__header__box2__return')

  .todo__main
    .todo__main__new
      .todo__main__new__box
        .todo__main__new__box__hyouzi1
          ="新しいToDoを作成"
        .todo__main__new__box__hyouzi2
          ="終了日"
      = form_for [@task,Todo.new] do |f|
        = f.text_field :todo, class: 'todo__main__new__form', placeholder: '新しいToDoを入力してください'
        = f.date_field :enddate, class: 'todo__main__new__date'
        = f.submit '作成', class: 'todo__main__new__btn'
    .todo__main__list
      - @task.todos.sort_by{|task|((task.enddate - @today).to_i)}.each do |task|
        .todo__main__list__to-do
          = task.todo
          = "終了日:#{task.enddate}"
          = "残り:#{((task.enddate - @today).to_i)}日"
          = "担当者:#{task.user.name}"
          = link_to "/tasks/:task_id/todos/#{task.id}", method: :delete do
            = icon('fas', 'trash-alt', class: 'todo__main__list__to-do__delete')
          

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 アカウント編集
      = link_to "ログアウト", destroy_user_session_path,method: :delete,class: 'btn'
      = link_to "トップページに戻る","/", class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'